export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_FALSE = 'GET_ADDRESS_FALSE';
export const DELETE_ADDRESS= 'DELETE_ADDRESS';


export const GET_WITHDRAW_REQUEST = 'GET_WITHDRAW_REQUEST';
export const GET_WITHDRAW_SUCCESS = 'GET_WITHDRAW_SUCCESS';
export const GET_WITHDRAW_FALSE = 'GET_WITHDRAW_FALSE';

export const RESET_ACCOUNT_REQUEST = 'RESET_ACCOUNT_REQUEST';
export const RESET_ACCOUNT_SUCCESS = 'RESET_ACCOUNT_SUCCESS';
export const RESET_ACCOUNT_FALSE = 'RESET_ACCOUNT_FALSE';