version: '3.6'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    expose:
      - 27017
    ports:
      - 27027:27017
    volumes:
      - ./data/mongodb/db/:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: rollup